apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: amrelzahar/simple-app
          ports:
            - containerPort: 3000
